version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      # 在这里同时安装主题和 Markdown 转换插件
      - pip install sphinx-rtd-theme m2r2

sphinx:
  configuration: docs/source/conf.py